### ISSUE TITLE
Black view

### ISSUE THREAD

**Issue by DiogoNeves** [KyoheiG3/DynamicBlurView#10]
Just followed the iOS 8+ example and applied it to an image view and it shows a completely black view.
Any ideas?

``` swift
    if let imageView = self.bannerImage {
        let blurView = DynamicBlurView(frame: imageView.bounds)
        blurView.blurRadius = 10
        imageView.addSubview(blurView)
    }
```

EDIT: This is called from `awakeFromNib()`

**Comment by DiogoNeves** [comment]
I just realised there's an extension specifically for images :)

**Comment by royherma** [comment]
getting this as well, for a view...any ideas?

**Comment by DiogoNeves** [comment]
I should have posted my solution.
For images there's a different method to call, here's my code

``` swift
        if let image = self.bannerImage?.image {
            let blurredImage = image.blurredImage(5.0, iterations: 3, ratio: 2.0, blendColor: nil)
            self.bannerImage?.image = blurredImage
        }
```

**Comment by royherma** [comment]
Appreciate the prompt response, but I was just adding the dynamic blur to a custom UIView, and it was strictly black (as you mentioned in your issue). So not applying to a UIImage, but still getting the result that you described.

**Comment by DiogoNeves** [comment]
If the view has an image in it, even if you're not applying directly to the image, I think it could still cause issues. Is that the case? (Try removing any images from sub views to test)

**Comment by orkenstein** [comment]
@royherma this happens to me when adding on a view, whose view controller is presented modally. Did you find any solution?
@

**Comment by DiogoNeves** [comment]
@orkenstein not sure if that's the same problem. The solution I found is shown above
https://github.com/KyoheiG3/DynamicBlurView/issues/10#issuecomment-169334196

**Comment by orkenstein** [comment]
@DiogoNeves Thanks, my issue is not about images. Continue my research.

**Comment by aatalyk** [comment]
Does anyone found a solution for black view?

**Comment by brod-ie** [comment]
Why is this issue closed?

**Comment by Tr736** [comment]
did you manage to solve this issue?

**Comment by haemi** [comment]
would be interested in this as well

**Comment by RSickenberg** [comment]
Same issue here, with empty UIView

**Comment by mohpor** [comment]
If anyone else is still having this issue:
https://github.com/KyoheiG3/DynamicBlurView/issues/32#issuecomment-371444748
