### ISSUE TITLE
@NSManaged attribute applied to non-CoreData property

### ISSUE THREAD

**Issue by Skogetroll** [KyoheiG3/DynamicBlurView#2]
There's some strange property declaration:

```
…
public class DynamicBlurView: UIView {
private class BlurLayer: CALayer {
    @NSManaged var blurRadius: CGFloat
…
```

And [official documentation](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/WritingSwiftClassesWithObjective-CBehavior.html) says this:

> Add the @NSManaged attribute before each property definition in your managed object subclass that corresponds to an attribute or relationship in your Core Data model. Like the @dynamic attribute in Objective-C, the @NSManaged attribute informs the Swift compiler that the storage and implementation of a property will be provided at runtime. **However, unlike @dynamic, the @NSManaged attribute is available _only_ for Core Data support.**

And it doesn't look like that BlurLayer is related to Core Data in _any_ way.

So, i think it's better to just to add some default value for blurRadius, or declare blurRadius as optional CGFloat, if the problem is in default value for this property.

**Comment by KyoheiG3** [comment]
I want to use `@dynamic` of Objective-C in Swift.

`blurRadius` is not related to the core data certainly.
However, the method to use `setValue:forKey:` and `valueForKey` also I tried, `displayLayer:` is not called.

This problem other than to use the `@NSManaged` was not able to resolve.
