### ISSUE TITLE
DynamicBlurView as subview of modal presented View Controller appear like view with black background

### ISSUE THREAD

**Issue by grishamsc** [KyoheiG3/DynamicBlurView#20]
At UIViewController i add DynamicBlurView as subview. After that i present that View Controller modaly and DynamicBlurView looks like just black view.

`
class BlurViewController: UIViewController {
  
  override func viewDidLoad() {
    super.viewDidLoad()
    view.backgroundColor = .clear

    let blur = DynamicBlurView(frame: CGRect(x: 20, y: 20, width: 300, height: 300))
    view.addSubview(blur)
    blur.blurRadius = 10
    blur.dynamicMode = .common
    
  }
`
![screen shot 2016-11-28 at 18 23 31](https://cloud.githubusercontent.com/assets/2726726/20673918/f2c8bb1c-b597-11e6-941a-3cae22d601b1.jpg)

**Comment by KyoheiG3** [comment]
`DynamicBlurView` can capture view in superview subviews only. if presented ViewController modaly that superview not has subviews.

**Comment by sssbohdan** [comment]
@grishamsc Hi, have you fixed this problem?

**Comment by pmusolino** [comment]
Actually, if you test the library with >iOS 10 it's not working.

**Comment by KyoheiG3** [comment]
@grishamsc @sssbohdan @Codeido Hi guys.
I'm improving this issue in #23 and supporting swift4.
But, It isn't supported for ios7. Also, it couldn't be completely synchronized with presenting the animation of modal.

Wait for swift4 release or clone [this branch](https://github.com/KyoheiG3/DynamicBlurView/tree/swift-4) and then try it.
Thank you.

**Comment by KyoheiG3** [comment]
[2.0.0](https://github.com/KyoheiG3/DynamicBlurView/releases/tag/2.0.0) was released.

**Comment by ghost** [comment]
I look like the issue still exist. without the dynamic blur i get a clearscreen after i add the blurview i get all black screen  without the blur

**Comment by KyoheiG3** [comment]
Did you set `true` to `isDeepRendering` ?

**Comment by scm573** [comment]
Yeah I had the same question and set isDeepRendering to true solved that.
Thanks!
