### ISSUE TITLE
is inaccessible due to 'private' protection level error

### ISSUE THREAD

**Issue by pepper28** [KyoheiG3/DynamicBlurView#28]
I'm running an IOS 9.2 application which includes DynamicBlurView.  It had been running without error and I just incurred 18 DynamicBlurView errors which states, "is inaccessible due to 'private' protection level error".  How should I correct this issue.

**Comment by KyoheiG3** [comment]
What version of Swift did you use? I guess that is 3.2. Should use greater than 4.0 please.

**Comment by pepper28** [comment]
Thanks, that was the issue.  Once I set my Swift from 3.2 to 4.0 problem went away.
