### ISSUE TITLE
Black boxes when scrolling collection view.

### ISSUE THREAD

**Issue by francocorreasosa** [KyoheiG3/DynamicBlurView#29]
Hello! I'm trying to add this lib to an app where we have an `UICollectionView` and when I scroll through the cells, some of them turn into a black box for a fraction of the second. And also some of the blurred images go to the wrong cell.

The problem happens when I scroll and change the blurView `alpha` to `0`. (that change is done automatically on scrolling outside a certain offset)

config:
```swift
        blurView.frame = textLabel.bounds
        blurView.drawsAsynchronously = true
        blurView.trackingMode = .tracking
        blurView.quality = .low
        blurView.isDeepRendering = true
        blurView.backgroundColor = .white
        blurView.iterations = 2
```

**Comment by KyoheiG3** [comment]
Although I tried it using Example, any problem didn't happen.
If you want to change the radius of blur with scroll offset, try to change `blurRatio` of view.

**Comment by zuil7** [comment]
Hi Good day,

I tried using your app. I notice that it converts white color after screenshot to black. Is there a way to not convert white to black after screenshot. Please see attachment

Thanks

<img width="385" alt="screen shot 2018-06-07 at 9 48 26 am" src="https://user-images.githubusercontent.com/1681118/41074495-06b3bd08-6a3b-11e8-9996-179290c295d6.png">
<img width="323" alt="screen shot 2018-06-07 at 9 48 48 am" src="https://user-images.githubusercontent.com/1681118/41074498-0b60adb6-6a3b-11e8-84df-59bb2116c206.png">

**Comment by KyoheiG3** [comment]
Hi @zuil7 
Could you set color for backgroundColor of the view?
Thanks.

**Comment by zuil7** [comment]
Hi,

still the same result i can see the black one. please see screenshot

<img width="326" alt="screen shot 2018-06-08 at 11 13 06 am" src="https://user-images.githubusercontent.com/1681118/41137344-4a71eb8c-6b0d-11e8-9cb5-db9ecc78062c.png">
<img width="361" alt="screen shot 2018-06-08 at 11 13 17 am" src="https://user-images.githubusercontent.com/1681118/41137345-4aac3b52-6b0d-11e8-9b2e-03e9d3bbf359.png">

**Comment by KyoheiG3** [comment]
What's color did you set?
If you set `.clear` or `nil`, the result becomes to be black.

**Comment by zuil7** [comment]
hi i set it to white. 

Here's a zip file of sample project

[DynamicTableBlur.zip](https://github.com/KyoheiG3/DynamicBlurView/files/2083369/DynamicTableBlur.zip)

**Comment by KyoheiG3** [comment]
I tried the sample project.
<img width="300" alt="2018-06-08 17 51 42" src="https://user-images.githubusercontent.com/5707132/41148893-0be96c7c-6b45-11e8-8fb7-e551c0b164e4.png">

It has to change backgroundColor of `Content View` that is on `UITableViewCell`.
<img width="361" alt="2018-06-08 17 53 53" src="https://user-images.githubusercontent.com/5707132/41148859-f82dc1ec-6b44-11e8-9ab0-0e8666688460.png">

**Comment by zuil7** [comment]
Thanks for this. Yeah now it works. 👍
