### ISSUE TITLE
'fromBlurRadius' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by iad24** [KyoheiG3/DynamicBlurView#31]
I install like this:
pod 'DynamicBlurView', '2.0.0'

![screen shot 2018-03-08 at 11 13 51 am](https://user-images.githubusercontent.com/15226261/37131145-0ad01dd4-22c2-11e8-868a-732286bbc1c0.png)

Around 18 compile errors!
Something i missed?

**Comment by KyoheiG3** [comment]
Hi @iad24 
What version of Swift did you use? Should use 4.0 or later.

**Comment by JamesJunsungKim** [comment]
I ran into the same issue here. Seems like the access-level for certain properties is set wrong so that it's not accessible. 

Swift version: 9.3

**Comment by KyoheiG3** [comment]
Swift version is not 9.3
Should check #33
