### ISSUE TITLE
Blur non-image views?

### ISSUE THREAD

**Issue by iad24** [KyoheiG3/DynamicBlurView#32]
Does this only blur UIImageViews? How bout other views? like buttons? Labels?

**Comment by KyoheiG3** [comment]
It is not only `UIImageView`. It can blur any views.

**Comment by iad24** [comment]
Oh ok. Need to use isDeepRendering right?
And its only available in v2.0.0?

**Comment by KyoheiG3** [comment]
It is not right. It can blur even if did not use `isDeepRendering`. The flag is for blur when presented view.

**Comment by iad24** [comment]
Oh ok. I think I made it to work without using isDeepRendering. 

But it seems it cannot blur dynamic views. Im actually trying to blur a camera screen. Example, you are using any camera app using the front lens. So you would see ur face in the screen, right? Then Im trying to blur it. Right now it just show black.

**Comment by KyoheiG3** [comment]
Did you try to blur of camera screen? I think it is impossible unfortunately because movie and camera layer cannot copy. If you want to blur a camera screen, you probably need to take pixel buffer and blur it.
