### ISSUE TITLE
Swift 4.1 . Support

### ISSUE THREAD

**Issue by kuchmiyalex** [KyoheiG3/DynamicBlurView#33]
Doesn't build under latest Xcode 9.3 with Swift 4.1 compiler.
Issue related to using `private` variables from DynamicBlurView extensions - so you just have to make them `fileprivate`

**Comment by luisfmelon** [comment]
I have the same problem.

**Comment by kuchmiyalex** [comment]
So probably underlying issue is that I'm using this lib in Swift 3.2 project via CocoaPods. It builds fine when used separately under XCode 9.3.
Anyways - I just made a pull request which fixes that issue #34

**Comment by KyoheiG3** [comment]
Hi guys.
Did you build in Swift 3.2? It is not supported. So I made a [branch](https://github.com/KyoheiG3/DynamicBlurView/tree/swift3) for swift3.
I do not think the downgrade is good, so please use the branch.

**Comment by luisfmelon** [comment]
Thank you so much for this!
