### ISSUE TITLE
How to apply dark mode?

### ISSUE THREAD

**Issue by whitesky77658** [KyoheiG3/DynamicBlurView#35]

**Comment by KyoheiG3** [comment]
Has to blend color using `blendColor` and `blendMode`.

**Comment by whitesky77658** [comment]
@KyoheiG3 Can you give me an example?

**Comment by whitesky77658** [comment]
@KyoheiG3 I tried this.
```
        self.blurOverlay.blendMode = .darken
        self.blurOverlay.blendColor = .black
```
But no changes.

**Comment by KyoheiG3** [comment]
It is impossible to make it dark mode.
```swift
view.iterations = 10
view.blendMode = .overlay
view.blendColor = .darkGray
```
It can make it a little like dark mode.

**Comment by Starsky89** [comment]
I achieved the dark mode:

blurView.blurRadius = 10
blurView.iterations = 5
blurView.blendMode = .multiply
blurView.blendColor = UIColor.darkGray.withAlphaComponent(0.7)

Cheers!
