### ISSUE TITLE
Type 'RunLoop' has no member 'Mode'

### ISSUE THREAD

**Issue by christianjavan** [KyoheiG3/DynamicBlurView#39]
Using XCode 9.4.1, swift 4.1, 

<img width="585" alt="captura de pantalla 2018-10-01 a la s 12 15 26" src="https://user-images.githubusercontent.com/4475349/46310255-b85fd800-c573-11e8-9060-6b84de96beb1.png">

And all pods installed correctly.
<img width="565" alt="captura de pantalla 2018-10-01 a la s 12 16 23" src="https://user-images.githubusercontent.com/4475349/46310311-ddece180-c573-11e8-94ec-f94e823de59e.png">

Any ideas on why?

**Comment by mwfire** [comment]
This is due to changes in Swift 4.2. If you are using Swift 4.1, the previous latest 2.X version should work for you.

Hope that helps :)

**Comment by sambo-visal** [comment]
I am using Xcode 9.4.
