### ISSUE TITLE
2018-11-06 14:33:45.734015+0800 TrainerApp[10915:215356] Could not cast value of type 'CALayer' (0x10552d730) to 'DynamicBlurView.BlurLayer' (0x10348cfd8).

### ISSUE THREAD

**Issue by liutian0117** [KyoheiG3/DynamicBlurView#40]

**Comment by KyoheiG3** [comment]
Please give me more context.

**Comment by liutian0117** [comment]
I’m sorry,it's working now, and I can’t reproduce it.
There is also a small issue here: how to achieve fade-in and fade-out animation effects?

**Comment by KyoheiG3** [comment]
Please try to change `blurRadius` or `alpha` in animations of `UIView.animate`.
Thanks.
