### ISSUE TITLE
Hi, Do you know how to get this effect? I would like the top edge of Visual Effect View to be invisible. Example :

### ISSUE THREAD

**Issue by janczakb** [KyoheiG3/DynamicBlurView#45]
Hi, Do you know how to get this effect? I would like the top edge of Visual Effect View to be invisible. Example :

![IMG_3066](https://user-images.githubusercontent.com/4959534/60621304-9c78b380-9ddd-11e9-93cf-75594dcf1a84.jpg)

**Comment by KyoheiG3** [comment]
I guess it uses `CAGradientLayer` from the middle.
