### ISSUE TITLE
DynamicBlurView 5.0: crash on convertToARGB8888()

### ISSUE THREAD

**Issue by LaurentiuUngur** [KyoheiG3/DynamicBlurView#50]
Hi ! First of all I would like to thank you for this library. After upgrading from 4.1 to 5.0 I get a crash from time to time. I'm using it along with [PopupDialog](https://github.com/Orderella/PopupDialog). This is the stack trace. Thank you !

 
<img width="1808" alt="Screenshot 2020-04-27 at 08 50 37" src="https://user-images.githubusercontent.com/13499785/80339024-75a4d580-8866-11ea-8a62-e29db682565f.png">

**Comment by KyoheiG3** [comment]
Hi @LaurentiuUngur 
Could you tell me Device details and os version?
Thanks.

**Comment by LaurentiuUngur** [comment]
iPhone 11 Pro iOS 13.4.1 Thanks !

**Comment by KyoheiG3** [comment]
please check 5.0.1.

**Comment by LaurentiuUngur** [comment]
I'll come back soon with a feedback. Thanks for the fast support !

**Comment by LaurentiuUngur** [comment]
Hi @KyoheiG3 ! It's not crashing anymore, but for whatever reason it seems the blur is not working anymore.

**Comment by KyoheiG3** [comment]
I don't have iPhone 11 Pro Device, So I can't try it.
Could you try the new version? 5.0.2 has released.

**Comment by LaurentiuUngur** [comment]
Hi @KyoheiG3 . It seems it's fixed. Thanks !
