### ISSUE TITLE
Compilation issue: var current: `Self` 

### ISSUE THREAD

**Issue by akshardarji** [KyoheiG3/DynamicBlurView#51]
Hello @KyoheiG3, 

'Self' is only available in a protocol or as the result of a method in a class; did you mean 'BlurLayer'?

```
var current: Self {
        presentation() ?? self
}
```

Hope for your soonest solutions. 

- DynamicBlurView pod version: [5.0.2]
- Xcode version: [11.3]
- Your application language: [Swift-4.2]

**Comment by KyoheiG3** [comment]
Hi @akshardarji 
Can you update Xcode to 11.4 or later? 5.0.2 requires Swift version 5.2.
Thanks.

**Comment by akshardarji** [comment]
@KyoheiG3 Thanks for your quick response.

I have discussed with my team for upgrading the Xcode 11.4, however, we can't do at the moment because of other dependencies hence can you show me any other way?

Hope for your soonest response.

**Comment by KyoheiG3** [comment]
@akshardarji You can try 5.0.3.
`Self` means `BlurLayer`, So it was changed.
Thanks.
