### ISSUE TITLE
Patch release include deployment target changes

### ISSUE THREAD

**Issue by shimastripe** [KyoheiG3/DynamicBlurView#58]
https://github.com/KyoheiG3/DynamicBlurView/pull/57

This PR includes master branch only.
Please release new patch version 🙏

**Comment by KyoheiG3** [comment]
[5.0.5](https://github.com/KyoheiG3/DynamicBlurView/tree/5.0.5) was tagged.

**Comment by shimastripe** [comment]
@KyoheiG3 Thank you for your swift tagged! I check it!
