### ISSUE TITLE
CGContextSetInterpolationQuality error

### ISSUE THREAD

**Issue by ky1ejs** [KyoheiG3/DynamicBlurView#8]
Here's that's spat out in the debugger:

```
<Error>: CGContextSetInterpolationQuality: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
```

**Comment by KyoheiG3** [comment]
Same problem with this?
http://stackoverflow.com/a/19377347

**Comment by ky1ejs** [comment]
Very potentially. Sorry that I've taken ages to get back to you on this. One of my colleagues started us off with using GPUImage instead, but thanks for making DynamicBlurView! I'm glad I have it to hand :smile:.
